### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Scathacheng** [nay2009/RNASeq_DESeq2#1]
hello, it seems you are using DESeq2 to analyze colon samples and IBD? 
I want to ask how do you choose your "design" in the DESeq2 code.
I noticed some design=~tissue+replicate+day, so what biological question is your interest? did you find your answer with DESeq2 and such design?

Thanks,
Jiacheng Dai

**Comment by nyudanin** [comment]
Hello! 

Yes, I had been analyzing immune cells in human gut tissues to understand how they differ. The experiment design was to test the same immune cell population in a few different tissues, which we had obtained two days in a row. So in DESeq2, my design needed to take into account the effect of the actual tissue, the biological replicate of the sample, and the day on which the sample was obtained. That way, we could distinguish whether the differences we saw were really because of the tissue they were in or just because of different times/replicates. 

Hope that helps :)
